version: "3"

services:
  app:
    image: app:latest
    build:
      context: .
      dockerfile: app.Dockerfile
    working_dir: /var/app
    container_name: app
    networks:
      - app_net
    volumes:
      - ./app:/var/app
    stdin_open: true
    tty: true 
    depends_on:
      - db
    command: ["ash"]
    #command: ["flask", "run", "--host=0.0.0.0", "--port=8000"]
  db:
    image: db:latest
    working_dir: /var/db
    #environment:
      #- FLASK_DEBUG=1
    build:
      context: .
      dockerfile: db.Dockerfile
    container_name: db
    stdin_open: true # docker run -i
    tty: true # docker run -t
    volumes:
      - ./db:/var/db
    networks:
      - app_net

network:
  - app_net
